try
    let x = something()
catch InvalidArgument
    print('Broken!')

try
    let x = http.get('https://github.com')
# alias exception to identifier
catch FileNotFound as err
    print('Error: {}'.format(err.message))
